import type { Hotel, City, Offer } from '@/types';

// Using Unsplash real images (already whitelisted in next.config.ts)
export const mockCities: City[] = [
  { id: '1', name: 'صنعاء', nameEn: "Sana'a", governorate: 'أمانة العاصمة', governorateEn: 'Amanat Al-Asimah', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', hotelCount: 24 },
  { id: '2', name: 'عدن', nameEn: 'Aden', governorate: 'عدن', governorateEn: 'Aden', image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80', hotelCount: 18 },
  { id: '3', name: 'مأرب', nameEn: 'Marib', governorate: 'مأرب', governorateEn: 'Marib', image: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=600&q=80', hotelCount: 7 },
  { id: '4', name: 'المكلا', nameEn: 'Mukalla', governorate: 'حضرموت', governorateEn: 'Hadramaut', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&q=80', hotelCount: 12 },
  { id: '5', name: 'تعز', nameEn: 'Taiz', governorate: 'تعز', governorateEn: 'Taiz', image: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=600&q=80', hotelCount: 9 },
  { id: '6', name: 'الحديدة', nameEn: 'Hodeidah', governorate: 'الحديدة', governorateEn: 'Hodeidah', image: 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=600&q=80', hotelCount: 6 },
];

export const mockHotels: Hotel[] = [
  {
    id: '1',
    name: 'فندق موفنبيك صنعاء',
    nameEn: "Movenpick Hotel Sana'a",
    slug: 'movenpick-sanaa',
    description: 'فندق فاخر في قلب صنعاء يوفر أرقى الخدمات وأجمل الإطلالات على المدينة',
    descriptionEn: "A luxury hotel in the heart of Sana'a offering premium services and stunning city views",
    city: 'صنعاء',
    cityEn: "Sana'a",
    governorate: 'أمانة العاصمة',
    governorateEn: 'Amanat Al-Asimah',
    address: 'شارع الستين، صنعاء',
    lat: 15.3694,
    lng: 44.1910,
    stars: 5,
    rating: 4.8,
    reviewCount: 324,
    priceFrom: 85,
    currency: 'USD',
    images: [
      'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=900&q=80',
    ],
    thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=600&q=80',
    amenities: [
      { id: 'a1', name: 'واي فاي مجاني', nameEn: 'Free WiFi', icon: 'wifi', category: 'general' },
      { id: 'a2', name: 'مسبح', nameEn: 'Pool', icon: 'pool', category: 'sport' },
      { id: 'a3', name: 'مطعم', nameEn: 'Restaurant', icon: 'utensils', category: 'dining' },
      { id: 'a4', name: 'موقف سيارات', nameEn: 'Parking', icon: 'parking', category: 'general' },
    ],
    rooms: [
      {
        id: 'r1-1', hotelId: '1', name: 'غرفة ديلوكس مزدوجة', nameEn: 'Deluxe Double Room',
        description: 'غرفة فسيحة بإطلالة رائعة على المدينة مع سرير مزدوج كبير وحمام خاص فاخر',
        capacity: 2, pricePerNight: 85, images: [], isAvailable: true,
        amenities: [
          { id: 'ra1', name: 'واي فاي', nameEn: 'WiFi', icon: 'wifi', category: 'general' },
          { id: 'ra2', name: 'تلفاز', nameEn: 'TV', icon: 'tv', category: 'room' },
          { id: 'ra3', name: 'مكيف هواء', nameEn: 'AC', icon: 'wind', category: 'room' },
        ],
      },
      {
        id: 'r1-2', hotelId: '1', name: 'جناح ملكي', nameEn: 'Royal Suite',
        description: 'جناح فاخر بغرفة معيشة مستقلة وإطلالة بانورامية استثنائية ومرافق VIP كاملة',
        capacity: 3, pricePerNight: 160, images: [], isAvailable: true,
        amenities: [
          { id: 'ra4', name: 'واي فاي', nameEn: 'WiFi', icon: 'wifi', category: 'general' },
          { id: 'ra5', name: 'جاكوزي', nameEn: 'Jacuzzi', icon: 'waves', category: 'room' },
          { id: 'ra6', name: 'غرفة معيشة', nameEn: 'Living Room', icon: 'sofa', category: 'room' },
        ],
      },
      {
        id: 'r1-3', hotelId: '1', name: 'غرفة اقتصادية', nameEn: 'Standard Room',
        description: 'غرفة مريحة بتجهيزات عصرية ومساحة كافية لضيف واحد أو اثنين',
        capacity: 2, pricePerNight: 55, images: [], isAvailable: false,
        amenities: [
          { id: 'ra7', name: 'واي فاي', nameEn: 'WiFi', icon: 'wifi', category: 'general' },
          { id: 'ra8', name: 'مكيف هواء', nameEn: 'AC', icon: 'wind', category: 'room' },
        ],
      },
    ],
    discount: { id: 'd1', percentage: 20, validFrom: '2025-01-01', validTo: '2025-12-31' },
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01',
  },
  {
    id: '2',
    name: 'فندق أزال عدن',
    nameEn: 'Azal Hotel Aden',
    slug: 'azal-aden',
    description: 'فندق راقٍ على شاطئ البحر العربي في مدينة عدن التاريخية',
    descriptionEn: 'An elegant hotel on the Arabian Sea coast in historic Aden city',
    city: 'عدن',
    cityEn: 'Aden',
    governorate: 'عدن',
    governorateEn: 'Aden',
    address: 'شارع الميناء، عدن',
    stars: 4,
    rating: 4.5,
    reviewCount: 187,
    priceFrom: 55,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=900&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80',
    amenities: [
      { id: 'a1', name: 'واي فاي مجاني', nameEn: 'Free WiFi', icon: 'wifi', category: 'general' },
      { id: 'a3', name: 'مطعم', nameEn: 'Restaurant', icon: 'utensils', category: 'dining' },
    ],
    rooms: [
      {
        id: 'r2-1', hotelId: '2', name: 'غرفة بإطلالة بحرية', nameEn: 'Sea View Room',
        description: 'غرفة رائعة بإطلالة مباشرة على البحر العربي مع شرفة خاصة',
        capacity: 2, pricePerNight: 65, images: [], isAvailable: true,
        amenities: [
          { id: 'rb1', name: 'واي فاي', nameEn: 'WiFi', icon: 'wifi', category: 'general' },
          { id: 'rb2', name: 'إطلالة بحرية', nameEn: 'Sea View', icon: 'waves', category: 'room' },
          { id: 'rb3', name: 'شرفة', nameEn: 'Balcony', icon: 'wind', category: 'room' },
        ],
      },
      {
        id: 'r2-2', hotelId: '2', name: 'غرفة ستاندرد', nameEn: 'Standard Room',
        description: 'غرفة مريحة بكافة المرافق الأساسية بسعر مناسب',
        capacity: 2, pricePerNight: 45, images: [], isAvailable: true,
        amenities: [
          { id: 'rb4', name: 'واي فاي', nameEn: 'WiFi', icon: 'wifi', category: 'general' },
          { id: 'rb5', name: 'مكيف هواء', nameEn: 'AC', icon: 'wind', category: 'room' },
        ],
      },
    ],
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01',
  },
  {
    id: '3',
    name: 'فندق المكلا الدولي',
    nameEn: 'Mukalla International Hotel',
    slug: 'mukalla-international',
    description: 'فندق دولي متميز في عاصمة محافظة حضرموت',
    descriptionEn: 'Distinguished international hotel in the capital of Hadramaut governorate',
    city: 'المكلا',
    cityEn: 'Mukalla',
    governorate: 'حضرموت',
    governorateEn: 'Hadramaut',
    address: 'شارع الساحل، المكلا',
    stars: 4,
    rating: 4.3,
    reviewCount: 98,
    priceFrom: 45,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=900&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80',
    amenities: [
      { id: 'a1', name: 'واي فاي مجاني', nameEn: 'Free WiFi', icon: 'wifi', category: 'general' },
    ],
    rooms: [],
    discount: { id: 'd2', percentage: 15, validFrom: '2025-01-01', validTo: '2025-06-30' },
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01',
  },
  {
    id: '4',
    name: 'فندق سبأ صنعاء',
    nameEn: "Saba Hotel Sana'a",
    slug: 'saba-sanaa',
    description: 'فندق متوسط مريح يقع في قلب صنعاء القديمة',
    descriptionEn: "Comfortable mid-range hotel in the heart of old Sana'a",
    city: 'صنعاء',
    cityEn: "Sana'a",
    governorate: 'أمانة العاصمة',
    governorateEn: 'Amanat Al-Asimah',
    address: 'صنعاء القديمة',
    stars: 3,
    rating: 4.0,
    reviewCount: 156,
    priceFrom: 30,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=900&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1445019980597-93fa8acb246c?w=600&q=80',
    amenities: [
      { id: 'a1', name: 'واي فاي مجاني', nameEn: 'Free WiFi', icon: 'wifi', category: 'general' },
    ],
    rooms: [],
    isFeatured: false,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01',
  },
  {
    id: '5',
    name: 'فندق غولدن موتيل عدن',
    nameEn: 'Golden Motel Aden',
    slug: 'golden-motel-aden',
    description: 'أحد أفضل الفنادق الاقتصادية في مدينة عدن',
    descriptionEn: 'One of the best budget hotels in Aden city',
    city: 'عدن',
    cityEn: 'Aden',
    governorate: 'عدن',
    governorateEn: 'Aden',
    address: 'خور مكسر، عدن',
    stars: 3,
    rating: 3.8,
    reviewCount: 72,
    priceFrom: 25,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1551882547-ff40c4fe1fa7?w=900&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1551882547-ff40c4fe1fa7?w=600&q=80',
    amenities: [],
    rooms: [],
    isFeatured: false,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01',
  },
  {
    id: '6',
    name: 'فندق بلقيس تعز',
    nameEn: 'Bilqis Hotel Taiz',
    slug: 'bilqis-taiz',
    description: 'فندق متميز يتمتع بإطلالة خلابة على مدينة تعز',
    descriptionEn: 'Distinguished hotel with a stunning view of Taiz city',
    city: 'تعز',
    cityEn: 'Taiz',
    governorate: 'تعز',
    governorateEn: 'Taiz',
    address: 'الحوبان، تعز',
    stars: 4,
    rating: 4.2,
    reviewCount: 115,
    priceFrom: 40,
    currency: 'USD',
    images: ['https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=900&q=80'],
    thumbnail: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=600&q=80',
    amenities: [
      { id: 'a1', name: 'واي فاي مجاني', nameEn: 'Free WiFi', icon: 'wifi', category: 'general' },
      { id: 'a3', name: 'مطعم', nameEn: 'Restaurant', icon: 'utensils', category: 'dining' },
    ],
    rooms: [],
    discount: { id: 'd3', percentage: 10, validFrom: '2025-01-01', validTo: '2025-12-31' },
    isFeatured: true,
    isActive: true,
    createdAt: '2024-01-01',
    updatedAt: '2024-12-01',
  },
];

export const mockOffers: Offer[] = [
  { id: '1', title: 'عروض صيف 2025', titleEn: 'Summer 2025 Deals', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=900&q=80', link: '/hotels', isActive: true, order: 1 },
  { id: '2', title: 'احجز مبكراً واوفر 30%', titleEn: 'Book Early Save 30%', image: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=900&q=80', link: '/hotels', isActive: true, order: 2 },
  { id: '3', title: 'عروض عيد الأضحى', titleEn: 'Eid Al-Adha Deals', image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=900&q=80', link: '/hotels', isActive: true, order: 3 },
];
